### ISSUE TITLE
Blanket implementation fails to compile due to missing enum variants. 

### ISSUE THREAD

**Issue by charles-r-earp** [bemeurer/cache-size#20]
In "blanket.rs", `CacheType` is an empty enum. But several functions look like this, with variants that are missing. The docs say that they simply return None, but do not compile. 
 
```
pub enum CacheType {}

/// Returns the line size in bytes of the L1 data cache.
///
/// This is the implementation for unsupported architectures, and always returns None.
#[inline]
pub fn l1_cache_line_size() -> Option<usize> {
    cache_line_size(1, CacheType::Data)
}
```

Unsupported architectures (ie not x86) should presumably have trivial implementations that return None, `CacheType` isn't needed.

**Comment by SUPERCILEX** [comment]
Since this repo might be dead, I published my own version with the fix: https://crates.io/crates/cache-size2

**Comment by lovesegfault** [comment]
Not dead, I'm just busy 😅 

I'll merge your PR and cut a release today. Thanks!

**Comment by SUPERCILEX** [comment]
Oh lol, sorry! I'll yank mine once the release is out.

**Comment by lovesegfault** [comment]
The release is out: https://crates.io/crates/cache-size/0.7.0

Thanks for the fix!

**Comment by SUPERCILEX** [comment]
Sweet, yanked!
