### ISSUE TITLE
Using `cache-size` outside x86 target causes it fail to build, not just unusable.

### ISSUE THREAD

**Issue by kennytm** [bemeurer/cache-size#3]
The README mentioned 

> Currently this crate only supports x86 CPUs, since it relies on the `CPUID` instruction, via the `raw_cpuid` crate. It is a goal to support other architectures; PRs are welcome!

We expected that this means outside of x86, this crate simply would return None on everything. Instead, it just fail to build due to the hard dependency of `raw_cpuid`

```
error[E0433]: failed to resolve: could not find `arch` in `self`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-7.0.3/src/lib.rs:50:37
   |
50 |         let result = unsafe { self::arch::__cpuid_count(a, c) };
   |                                     ^^^^ could not find `arch` in `self`
```

It would be nice if depending on `cache-size` is still possible outside x86.

**Comment by lovesegfault** [comment]
Thanks for the report @kennytm!

I'll work on adding blanket support for other arches today.

**Comment by lovesegfault** [comment]
@kennytm Done, now unless the arch is a supported one the user will get a blanket implementation thay yields `None`s all the time.

Let me know if you're happy with this and I'll cut a new release today :)

**Comment by lovesegfault** [comment]
Alright, I've tested this on my AArch64 machine, and will be cutting a new release now that I know it works

**Comment by lovesegfault** [comment]
Done :)

**Comment by kennytm** [comment]
Thanks for the quick fix! 😄

**Comment by lovesegfault** [comment]
Glad it's being used!
